---
- name: Evaluate {{ codeready_project }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ codeready_project }}'
    state: present

- name: Evaluate CodeReady CatalogSourceConfig
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'codeready-csc.yaml.j2') }}"

- name: Evaluate CodeReady Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'codeready-subscription.yaml.j2') }}"

- name: Wait for CodeReady operator to install
  k8s_facts:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: 'crwoperator.v1.2.0'
      namespace: '{{ codeready_project }}'
  register: csv_status
  until: (csv_status.resources is defined) and (csv_status.resources|length>0) and (csv_status.resources[0].status.phase == 'Succeeded')
  retries: 10
  delay: 30

- name: Evaluate CodeReady Cluster
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'codeready-cluster.yaml.j2') }}"

- name: Wait for codeready to be running
  uri:
    url: http://codeready-{{ codeready_project }}.{{ route_suffix }}/api/system/state
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 30
