---
- name: "Uninstall DIL Streaming Workshop"
  hosts: workshop
  tasks:
    - include_role:
        name: uninstall_codeready
      vars:
        codeready_project: "codeready"
      tags: uninstall_codeready
    - include_role:
        name: uninstall_streams
      vars:
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: uninstall_online
      vars:
        operators_project: "workshop-operators"
      tags: provision_online
    - include_role:
        name: uninstall_project
      loop:
        - "workshop-operators"
        - "shared-db-earth" 
        - "shared-kafka-earth"
        - "shared-app-earth"
      tags: remove_workshop_projects
    - include_role:
        name: uninstall_user_projects
      with_sequence: start=1 end={{ usersno }} format=user%d
      tags: uninstall_user_projects
