---
- name: "Uninstall DIL Streaming Workshop"
  hosts: workshop
  tasks:
    - include_role:
        name: uninstall_streams
      vars:
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: uninstall_online
      vars:
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: uninstall_project
      loop:
        - "workshop-operators"
        - "shared-db-earth" 
        - "shared-kafka-earth"
      tags: provision_streams
