apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingconsole-config
data:
  application.properties: |2+
    camel.component.infinispan.configuration.configurationUri=client.properties
  client.properties: |2+
    infinispan.client.hotrod.use_auth=true
    infinispan.client.hotrod.auth_username=developer
    infinispan.client.hotrod.auth_password=8JPd39uSeTtNcy7e
    infinispan.client.hotrod.auth_realm=default
    infinispan.client.hotrod.sasl_mechanism=SCRAM-SHA-512
    infinispan.client.hotrod.marshaller=org.infinispan.commons.marshall.JavaSerializationMarshaller
    infinispan.client.hotrod.java_serial_whitelist=java.util.ArrayList,java.util.LinkedHashMap
    infinispan.client.hotrod.async_executor_factory = org.infinispan.client.hotrod.impl.async.DefaultAsyncExecutorFactory
    infinispan.client.hotrod.default_executor_factory.pool_size = 1
    infinispan.client.hotrod.hash_function_impl.2 = org.infinispan.client.hotrod.impl.consistenthash.ConsistentHashV2
    infinispan.client.hotrod.tcp_no_delay = true
    infinispan.client.hotrod.tcp_keep_alive = false
    infinispan.client.hotrod.request_balancing_strategy = org.infinispan.client.hotrod.impl.transport.tcp.RoundRobinBalancingStrategy
    infinispan.client.hotrod.key_size_estimate = 64
    infinispan.client.hotrod.value_size_estimate = 512
    infinispan.client.hotrod.force_return_values = false
