---
- name: Process user namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: 'user{{ item }}'
    state: present

- name: Give user{{ item }} access to projects
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-rolebinding.yaml.j2') }}"
  loop:
    - { user: 'user{{ item }}', namespace: 'user{{ item }}', role: 'admin' }
    - { user: 'user{{ item }}', namespace: '{{ kafka_earth_namespace }}', role: 'view' }