---
# - name: "Get master config"
#   hosts: master
#   gather_facts: no
#   tasks:
#   - include_role:
#       name: master_config

- name: "Install DIL Streaming Workshop"
  hosts: workshop
  tasks:
    - include_role:
        name: provision_streams
      vars:
        streams_version: "1.1.0"
        kafka_earth_namespace: "shared-kafka-earth"
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: provision_online
      vars:
        online_version: "0.28.0"
        operators_project: "workshop-operators"
      tags: provision_online
    - include_role:
        name: provision_shared
      vars:
        db_earth_namespace: "shared-db-earth"
        kafka_earth_namespace: "shared-kafka-earth"
      tags: provision_streams
    - include_role:
        name: user_projects
      with_sequence: start=1 end={{ usersno }} format=%d
      vars:
        kafka_earth_namespace: "shared-kafka-earth"
      tags: user_projects