---
- name: "Install DIL Streaming Workshop"
  hosts: workshop
  tasks:
    - include_role:
        name: provision_streams
      vars:
        streams_version: "1.1.0"
        kafka_earth_namespace: "shared-kafka-earth"
        operators_project: "workshop-operators"
      tags: provision_streams
    - include_role:
        name: provision_online
      vars:
        online_version: "0.28.2"
        operators_project: "workshop-operators"
    - include_role:
        name: provision_shared
      vars:
        db_earth_namespace: "shared-db-earth"
        kafka_earth_namespace: "shared-kafka-earth"
      tags: provision_streams
    - include_role:
        name: user_projects
      with_sequence: start=1 end={{ usersno }} format=%d
      vars:
        db_earth_namespace: "shared-db-earth"
        kafka_earth_namespace: "shared-kafka-earth"
      tags: user_projects
