---
- name: Evaluate {{ operators_project }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: workshop-operators
    namespace: '{{ operators_project }}'

- name: Evaluate Online Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'online-subscription.yaml.j2') }}"

- name: Wait for Online operator to install
  k8s_facts:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: 'amqonline.{{ online_version }}'
      namespace: '{{ operators_project }}'
  register: csv_status
  until: >-
    (csv_status.resources is defined) 
    and (csv_status.resources|length>0) 
    and (csv_status.resources[0].status is defined) 
    and (csv_status.resources[0].status.phase is defined) 
    and (csv_status.resources[0].status.phase == 'Succeeded')
  retries: 10
  delay: 30

- name: Add the Security Constraint Context
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'scc-185.yaml.j2') }}"

- name: Set temp dir
  set_fact:
    amq_online_tmp: "/tmp/amq-online"

- name: Ensure example directory exists
  file:
    path: '{{ amq_online_tmp }}'
    state: directory

- name: Download example files
  unarchive:
      src: https://access.redhat.com/node/4306051/423/0/14663711
      dest: '{{ amq_online_tmp }}'
      creates: '{{ amq_online_tmp }}/install'
      remote_src: yes

- name: Create Online Plan Examples
  k8s:
    state: present
    namespace: '{{ operators_project }}'
    src: '{{ item }}'
  with_fileglob:
    - '{{ amq_online_tmp }}/install/components/example-plans/*'
    - '{{ amq_online_tmp }}/install/components/example-authservices/standard-authservice.yaml'
