---

- name: Get user token from OpenShift
  k8s_auth:
    host: https://{{ api_domain }}:6443
    validate_certs: false
    username: 'user{{ item }}'
    password: openshift
  register: k8s_auth_results

- name: See k8s_auth_results
  debug:
    msg: '{{ k8s_auth_results }}'

- name: Extract User Token from OpenShift
  set_fact:
    user_token: '{{ k8s_auth_results.k8s_auth.api_key }}'



- name: Get Che Access Token from Keycloack
  uri:
    url: http://keycloak-{{ che_project }}.{{ route_subdomain }}/auth/realms/che/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
    - [ client_id, che-public ]
    - [ subject_issuer, openshift-v4 ]
    - [ subject_token, '{{ user_token }}' ]
    - [ grant_type, urn:ietf:params:oauth:grant-type:token-exchange ]
    - [ subject_token_type, urn:ietf:params:oauth:token-type:access_token]
    status_code: '200'
  register: access_token_result

- name: Extract Access Token from Keycloack from result
  set_fact:
    access_token: '{{access_token_result.json.access_token}}'

- name: Get User id from Che Keycloak
  uri:
    url: http://keycloak-{{ che_project }}.{{ route_subdomain }}/auth/realms/che/protocol/openid-connect/userinfo
    method: GET
    headers:
      Authorization: 'Bearer {{ access_token }}'
    body_format: form-urlencoded
    body:
    - [ username, 'user{{ item }}' ]
    status_code: '200'
  register: access_token_result

- name: Extract Access Token from Keycloack from result
  set_fact:
    user_id: '{{access_token_result.json.sub}}'


- name: Update User Details
  uri:
    url: http://keycloak-{{ che_project }}.{{ route_subdomain }}/auth/admin/realms/che/users/{{ user_id }}
    method: PUT
    headers:
      Authorization: 'Bearer {{ admin_token }}'
    body_format: json
    body: '{
      "email":"user{{ item }}@example.com",
      "firstName":"user",
      "lastName":"{{ item }}",
      "enabled":"true"
    }'
    status_code: '204'
  register: update_result